### ISSUE TITLE
Error CS9057 - Analyzer assembly version issue

### ISSUE THREAD

**Issue by MrGeneric** [mrpmorris/Fluxor#519]
Hey,
I ran into this error after updating from 6.1.0 to 6.2.1.5. The project built fine for me locally as I have the latest version of Visual Studio that includes the .NET 9 SDK. It failed on the build server though and locally for a colleague who has the .NET 8 SDK (8.0.404). 

> Error CS9057: The analyzer assembly 'C:\windows\ServiceProfiles\NetworkService\.nuget\packages\fluxor.blazor.web\6.2.1.5\analyzers\dotnet\cs\Fluxor.Blazor.Web.Analyzers.dll' references version '4.12.0.0' of the compiler, which is newer than the currently running version '4.9.0.0'

For the moment I have rolled back the update, but just wanted to report it in case others run into the same.

Thanks.

**Comment by mrpmorris** [comment]
Fixed in 6.3 (hopefully)
Could you try again, please?

**Comment by MrGeneric** [comment]
I just tested both 6.3 and 6.4 and can confirm that the issue is resolved. Thank you!
